[Scheme]
Name=Vivid Life · Twilight · Purple
ColorForeground=#f5f5f5
ColorBackground=#333333
ColorCursor=#d8b4fe
ColorCursorForeground=#333333
ColorCursorUseDefault=FALSE
ColorSelection=#f5f5f5
ColorSelectionBackground=#655a70
ColorSelectionUseDefault=FALSE
ColorBoldUseDefault=TRUE
TabActivityColor=#fef9c3
ColorPalette=#171717;#fca5a5;#bef264;#fde047;#93c5fd;#d8b4fe;#67e8f9;#d4d4d4;#a3a3a3;#fee2e2;#ecfccb;#fef9c3;#dbeafe;#f3e8ff;#cffafe;#f5f5f5
