[Scheme]
Name=Vivid Life · Dawn · Purple
ColorForeground=#171717
ColorBackground=#d4d4d4
ColorCursor=#7e22ce
ColorCursorForeground=#d4d4d4
ColorCursorUseDefault=FALSE
ColorSelection=#171717
ColorSelectionBackground=#ba9fd2
ColorSelectionUseDefault=FALSE
ColorBoldUseDefault=TRUE
TabActivityColor=#713f12
ColorPalette=#171717;#991b1b;#3f6212;#854d0e;#1e40af;#6b21a8;#155e75;#d4d4d4;#525252;#7f1d1d;#365314;#713f12;#1e3a8a;#581c87;#164e63;#f5f5f5
